#!/bin/bash

fzf_command() {
  [ ! "$TMUX" ] && fzf "$@" || fzf-tmux "$@"
}

print_file() {
  cat <<EOF
File: "$1"
\`\`\`$(basename "$1" | rev | cut -d. -f1 | rev)
$(cat "$1")
\`\`\`
EOF
  echo
}

export -f print_file

[ $# -eq 1 ] && cd "$1"

if git rev-parse --git-dir >/dev/null 2>&1; then
  git ls-files --exclude-standard --others --cached
else
  find . -type f
fi |
  fzf_command --multi --ansi --filepath-word --preview='bat {}' --bind ctrl-t:toggle-all |
  tee /tmp/sdai-files-cache.txt |
  xargs -I{} bash -c 'print_file "{}"'
