#!/bin/sh

# sauce: https://gitlab.com/maister/doitbib/-/blob/master/dtb?ref_type=heads

BLUEFG=$'\033[0;34m'
REDFG=$'\033[0;31m'
GREENFG=$'\033[0;32m'
YELLOWFG=$'\033[0;33m'
MAGENTAFG=$'\033[0;35m'
CYANFG=$'\033[0;36m'
FGRESET=$'\033[0m'

usage() {
	printf "Provide a PDF filename or a DOI number and a BibTeX file.\n";
	printf "    Usage: %b${basename $0} %b<PDF> %b<bib>%b\n" "$GREENFG" "$MAGENTAFG" "$YELLOWFG" "$FGRESET";
	printf "    Usage: %b${basename $0} %b<DOI> %b<bib>%b\n" "$GREENFG" "$MAGENTAFG" "$YELLOWFG" "$FGRESET";
	printf "Remember to check that a BibTeX entry was found for your article.\n";
	exit
}

[ -z "$1" ] && usage

if [ -f "$1" ]; then
	DOI=$(pdfinfo "$1" | grep -io "doi:.*" | grep -o "10.[^)^ ]*") ||
	DOI=$(pdftotext "$1" 2>/dev/null - | grep -io "doi:.*" -m 1 | grep -o "10.[^)^ ]*") ||
	DOI=$(pdftotext "$1" 2>/dev/null - | grep -io "doi\\.org/.*" -m 1 | grep -o "10.[^)^ ]*") ||
	exit 1
else
	DOI="$1"
fi

printf "Downloading bibliographies for %s...\n" "$1"
curl -s "http://api.crossref.org/works/$DOI/transform/application/x-bibtex" -w '\n\n'
