#!/bin/bash

command -v diffix &>/dev/null || echo "diffix required"

id=${1:-new}
file=/tmp/sdai-conv-$id.md
filediff=/tmp/sdai-conv-$id.diff

content=$(cat "$file" | sed -n '/^```diff$/,/^```$/p' | sed '/^```/d')

echo "$content" >$filediff

# nvim $filediff

### Else just patch the latest response
patch --strip=1 --verbose < <(cat $filediff | diffix)
