#!/bin/bash

BASE_URL="https://api.binance.com/api/v3/ticker/price?symbol="

one=$(curl --silent "${BASE_URL}SUIUSDT" | jq '.price | tonumber' | cut -c1-4 &)
# two=$(curl --silent "${BASE_URL}APTUSDT" | jq '.price | tonumber' | cut -c1-4 &)

wait

echo \$"$(echo "24.733 * $one" | bc)"
