#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
elif [ $USER = dungngo ]; then
  selected=$(find ~/dev -mindepth 1 -maxdepth 1 -type d | fzf)
elif [ $USER = qd ]; then
  selected=$(find ~/Dev/work ~/Dev/personal ~/Study ~/Documents/Obsidian-Vault/ -mindepth 1 -maxdepth 1 -type d | fzf)
elif [ $USER = vpn ]; then
  selected=$(find ~/Desktop/DungNgo -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
