#!/usr/bin/env bash

start() {
    ### no audio
    ffmpeg -f x11grab -i :1 -c:v h264 ~/Videos/rec-$(date +%Y%m%d-%H%M).mkv &
    ### yes audio
    # ffmpeg -f x11grab -i :1 -f pulse -i default -c:v h264 ~/Videos/rec-$(date +%Y%m%d-%H%M).mkv &
    echo $! > /tmp/recpid

    screenkey -p fixed -g 800x100+1700+1300 --opacity 0.4 &
    echo $! > /tmp/screenkeypid

    notify-send -t 1000 "Recording started"
}

end() {
    kill -15 $(cat /tmp/recpid /tmp/screenkeypid) && rm -f /tmp/recpid /tmp/screenkeypid
    notify-send -t 1000 "Recording stopped"
}

[[ -f /tmp/recpid ]] && end || start
