#!/usr/bin/env bash

start() {
    SLOP=$(slop -f "%x %y %w %h %g %i") || exit 1
    read -r X Y W H G ID <<< $SLOP
    REGION="-s ${W}x${H} -i ${DISPLAY}+${X},${Y}"

    format="mp4"

    ### no audio
    ffmpeg -f x11grab $REGION -c:v h264 ~/Videos/rec-$(date +%Y%m%d-%H%M).$format &
    ### yes audio
    # ffmpeg -f x11grab $REGION -f pulse -i default -c:v h264 ~/Videos/rec-$(date +%Y%m%d-%H%M).$format &
    echo $! > /tmp/recpid

    # width and height of the window, x and y are where window start on the monitor
    # so screenkey should be relative to the width and height plus x and y
    screenkey -p fixed -g "$(($W * 23/100))x$(($H * 8/100))+$(($X + $W * 3/4))+$(($Y + $H * 9/10))" --opacity 0.4 &
    echo $! > /tmp/screenkeypid

    notify-send -t 1000 "Recording started"
}

end() {
    kill -15 $(cat /tmp/recpid /tmp/screenkeypid) && rm -f /tmp/recpid /tmp/screenkeypid
    notify-send -t 1000 "Recording stopped"
}

[[ -f /tmp/recpid && -f /tmp/screenkeypid ]] && end || start
