import = [
    "~/.config/alacritty/themes/themes/zenwritten_light.toml",
]

working_directory = "/Users/vpn"

[shell]
program = "/usr/local/bin/zsh"
args = ["--login"]

[font]
size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1
