[general]
import = [
    "~/.config/alacritty/themes/themes/nvim_light.toml",
]

working_directory = "/home/qd"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]

[window]
decorations = "none"
opacity = 0.96

[font]
size = 12.0

[font.normal]
# family = "BerkeleyMono Nerd Font Mono"
family = "Iosevka Nerd Font"

[font.offset]
x = 0
y = 2

[font.glyph_offset]
y = 2
