[general]
import = [
    "~/.config/alacritty/themes/themes/nvim_light.toml",
]

working_directory = "/home/qd"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]

[window]
decorations = "none"
opacity = 0.96

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 2

[font.glyph_offset]
y = 2
