#!/bin/bash

command -v fzf &> /dev/null || echo "fzf required. Installation: brew install fzf"

process_files() {
  while IFS= read -r file; do
    local ext=$(basename $file | rev | cut -d. -f1 | rev)
    echo "File: $file"
    echo "\`\`\`$ext"
    cat -n "$file"
    echo '```'
    echo
  done <<< "$1"
}

if [ $# -eq 0 ]; then
  echo "Usage: catai [file extension | manual] [-]"
  exit 0
fi

option="$1"

case "$option" in
  "m"|"manual")
    if git rev-parse --git-dir > /dev/null 2>&1; then
      files=$(git ls-files --exclude-standard --others --cached)
    else
      files=$(find . -type f)
    fi

    selected_files=$(
      echo "$files" \
      | fzf-tmux \
        -m --ansi --filepath-word \
        --preview='bat --theme=Dracula --color=always --style=numbers --line-range=:100 {}' \
        --bind ctrl-t:toggle-all
    )
    ;;

  *)
    selected_files=$(
      find . -type f -name "*.$option" \
        -not -path "./node_modules/*" \
        -not -path "./build/*"
    )
    ;;
esac

[[ ! -z "$selected_files" ]] && output=$(process_files "$selected_files")

if [ -z "$2" ]; then
  [ "$(uname)" = "Darwin" ] && echo "$output" | pbcopy
  [ "$(uname)" = "Linux" ] && echo "$output" | wl-copy
else
  echo "$output"
fi
