#!/bin/bash

process_files() {
  local selected_files="$1"
  local output=""

  while IFS= read -r file; do
    output+="File: $file"$'\n'
    output+="\`\`\`"$'\n'
    output+=$(cat -n "$file")$'\n'
    output+="\`\`\`"$'\n\n'
  done <<< "$selected_files"

  echo "$output"
}

if [ $# -eq 0 ]; then
  echo "Usage: $0 [query | manual]"
  exit 0
fi

option="$1"

case "$option" in
  "m"|"manual")
    if git rev-parse --git-dir > /dev/null 2>&1; then
      files=$(git ls-files --exclude-standard --others --cached)
    else
      files=$(find . -type f)
    fi

    selected_files=$(
      echo "$files" \
      | fzf -m --ansi --filepath-word \
        --preview='bat --theme=Dracula --color=always --style=numbers --line-range=:100 {}' \
        --bind ctrl-t:toggle-all
    )
    ;;

  *)
    selected_files=$(
      find . -type f -name "*.$option" \
        -not -path "./node_modules/*" \
        -not -path "./build/*"
    )
    ;;
esac

output=$(process_files "$selected_files")

if [ "$stdout" = false ]; then
  [ "$(uname)" = "Darwin" ] && echo "$output" | pbcopy
  [ "$(uname)" = "Linux" ] && echo "$output" | wl-copy
else
  echo "$output"
fi
