#!/bin/bash

tag=$(curl -sS https://api.github.com/repos/MystenLabs/sui/releases/latest | jq -r '.tag_name')

[[ "$(uname)" = "Darwin" ]] && os=macos
[[ "$(uname)" = "Linux" ]] && os=ubuntu

read -p "Continue download $tag for $os? (Y/N): " confirm && [[ $confirm == [yY] ]] || exit 1

curl -L "https://github.com/MystenLabs/sui/releases/download/$tag/sui-$tag-$os-x86_64.tgz" --output "sui-$tag-$os-x86_64.tgz"
