#!/bin/bash

file=/tmp/sdai-conv-000000.md

[[ "$1" = "m" ]] && file=$(
  ls /tmp/sdai-conv* \
  | fzf --height ~50% --preview 'bat --theme=Dracula --line-range=:500 {}'
)

patch --strip=1 --verbose < <(cat "$file" | sed -n '/^```diff$/,/^```$/p' | sed '/^```/d' | diff-fix)
