#!/bin/bash

LOG_FILE="/tmp/sdai-session-$(date +%s).log"
BASE_URL="https://admin.skydeck.ai/api/v1"
REFERER="https://eastagile.skydeck.ai/"

post_user_message() {
  local message="$1"
  local model_id="$2"
  local conversation_id="$3"
  local data

  if [[ -z "$conversation_id" ]]; then
    data='{ "message": "'"$message"'", "model_id": '"$model_id"', "regenerate_message_id": -1 }'
  else
    data='{ "message": "'"$message"'", "model_id": '"$model_id"', "conversation_id": '"$conversation_id"', "regenerate_message_id": -1 }'
  fi

  # echo "$data" >> "$LOG_FILE"

  curl -s -X POST "$BASE_URL/conversations/chat_v2/" \
    -H "Content-Type: application/json" -H "Cookie: eastagile_sessionid=$COOKIES" -H "Referer: $REFERER" \
    -d "$data"
}

get_response_stream() {
  local message_id="$1"

  if [[ "$beautify" = true ]]; then
    curl -s --no-buffer -X GET "$BASE_URL/conversations/streaming/?message_id=$message_id" \
      -H "Cookie: eastagile_sessionid=$COOKIES" -H "Referer: $REFERER" \
    | bat --style=grid --paging=never --theme=Dracula --language md
  else
    curl -s --no-buffer -X GET "$BASE_URL/conversations/streaming/?message_id=$message_id" \
      -H "Cookie: eastagile_sessionid=$COOKIES" -H "Referer: $REFERER"
    echo ""
  fi
}

get_conversation_id() {
  curl -s "$BASE_URL/conversations/" \
    -H "Content-Type: application/json" -H "Cookie: eastagile_sessionid=$COOKIES" -H "Referer: $REFERER" \
  | jq -c '.results[] | { id, name }' \
  | fzf \
  | jq '.id'
}

delete_conversation() {
  curl -s -X DELETE "$BASE_URL/conversations/$(get_conversation_id)" \
    -H "Content-Type: application/json" -H "Cookie: eastagile_sessionid=$COOKIES" -H "Referer: $REFERER" | jq '.message'
}

patch_conversation() {
  local name="$@"
  curl -s -X PATCH "$BASE_URL/conversations/$(get_conversation_id)" \
    -H "Content-Type: application/json" -H "Cookie: eastagile_sessionid=$COOKIES" -H "Referer: $REFERER" \
    -d '{ "name": "'"$name"'" }'
}

start_chat_session() {
  bg='\e[1;32m'
  fg1='\e[1;37m'
  fg2='\e[1;33m'
  clr='\e[0m'

  model_id=4094
  conversation_id=""
  [[ "$use_editor" = true ]] && tempfile=$(mktemp)

  while true; do
    printf "$fg1:Ctrl+D sends:$clr "

    if [[ "$use_editor" = true ]]; then
      nvim "$tempfile"
      message=$(cat "$tempfile")
    else
      message=$(cat)
    fi

    message=$(echo "$message" | awk '{gsub(/"/, "\\\""); printf "%s\\n", $0}')

    response=$(post_user_message "$message" "$model_id" "$conversation_id")
    conversation_id=$(echo "$response" | jq -r '.data.conversation_id')
    assistant_message_id=$(echo "$response" | jq -r '.data.assistant_message_id')

    get_response_stream "$assistant_message_id"

    [[ "$use_editor" = true ]] && read justwaitingforusertogo
  done
}

beautify=true
use_editor=false

action="$1"
shift

for arg in "$@"; do
  case "$arg" in
    "--no-color")
      beautify=false
      ;;
    "--editor")
      use_editor=true
      ;;
    *)
      ;;
  esac
done

case "$action" in
  "delete")
    delete_conversation
    ;;
  "patch")
    patch_conversation
    ;;
  "chat")
    start_chat_session
    ;;
esac
