#!/bin/bash

BASE_URL="https://admin.skydeck.ai/api/v1"
CURRENT_RESPONSE_FILE="/tmp/sdai-conv-000000.md"
CACHE_FILE="/tmp/sdai-cache.txt"
CACHE_TIMEOUT=300  # 5 minutes

COOKIE_FILE="$HOME/.sdai/cookies"
HEADER_REFERER="Referer: https://eastagile.skydeck.ai/"

BG='\e[1;32m'
CLR='\e[0m'

MODELS_NAMES=(
  "claude" "gpt4o" "gpt4o-mini" "groq-llama" "groq-mixtral"
)
MODELS_IDS=(
   4190 4094 4430 4455 4456
)

streaming="false"
conversation_id=""
assistant_message_id=""

model_index=0
model_name=${MODELS_NAMES[$model_index]}
model_id=${MODELS_IDS[$model_index]}

shopt -s expand_aliases
alias editor="nvim"
# alias editor="nvim -c 'set filetype=markdown'"
# alias editor="code -w"

spinner() {
  local rest=""
  local spinstr='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'

  while true; do
    printf " %s " "${spinstr:0:1}"
    rest=${spinstr#?}
    spinstr=$rest${spinstr:0:1}
    sleep 0.1
    printf "\b\b\b"
  done
}

pick_model() {
  selected=$(printf '%s\n' "${MODELS_NAMES[@]}" | fzf --prompt="Select a model: ")
  if [[ -n "$selected" ]]; then
    for i in "${!MODELS_NAMES[@]}"; do
      if [[ "${MODELS_NAMES[$i]}" = "${selected}" ]]; then
        model_name="${MODELS_NAMES[$i]}"
        model_id="${MODELS_IDS[$i]}"
        echo "Model changed to $model_name (ID: $model_id)"
        break
      fi
    done
  else
    echo "Model selection cancelled"
  fi
}

invalidate_cache() {
  [[ -f "$CACHE_FILE" ]] && rm $CACHE_FILE
}

refresh() {
  local exp=$(
    grep "_access" $COOKIE_FILE | cut -f7 | cut -d. -f2 | base64 -d 2>/dev/null \
      | grep -o '"exp":[0-9]*' | cut -d: -f2
  )

  [ "$(date +%s)" -gt "$exp" ] && \
    curl -s -X POST -o /dev/null "$BASE_URL/authentication/token/refresh/" \
      -H "$HEADER_REFERER" --cookie "$COOKIE_FILE" --cookie-jar "$COOKIE_FILE"
}

call() {
  refresh
  curl -s --cookie "$COOKIE_FILE" -H "Content-Type: application/json" -H "$HEADER_REFERER" "$@"
}

get_conversations() {
  if [ -f "$CACHE_FILE" ] && [ $(($(date +%s) - $(stat -f %m "$CACHE_FILE"))) -lt $CACHE_TIMEOUT ]; then
    cat "$CACHE_FILE"
  else
    call "$BASE_URL/conversations/" | tee "$CACHE_FILE"
  fi
}

get_conversation_id() {
  local response=$(get_conversations)
  echo $response | jq -c '.results[] | { id, name, size }' | fzf | jq '.id'
}

delete_conversation() {
  local conversation_id=$(get_conversation_id)
  call "$BASE_URL/conversations/$conversation_id" -o /dev/null -X DELETE &
  invalidate_cache
}

patch_conversation() {
  local conversation_id=$(get_conversation_id)
  [[ -z "$conversation_id" ]] && echo "No conversation selected" && exit 1

  local name
  read -p "Enter new name: " name
  call "$BASE_URL/conversations/$conversation_id" -o /dev/null -X PATCH -d '{ "name": "'"$name"'" }' &
}

post_user_message() {
  local message="$1"
  local model_id="$2"
  local conversation_id="$3"
  local data

  if [[ -z "$conversation_id" ]]; then
    data='{ "message": '"$message"', "model_id": '"$model_id"', "regenerate_message_id": -1 }'
  else
    data='{ "message": '"$message"', "model_id": '"$model_id"', "conversation_id": '"$conversation_id"', "regenerate_message_id": -1 }'
  fi

  call "$BASE_URL/conversations/chat_v2/" -d "$data"
}

get_response_stream() {
  streaming="true"
  call "$BASE_URL/conversations/streaming/?message_id=$assistant_message_id" --no-buffer | tee $CURRENT_RESPONSE_FILE
  streaming="false"
}

stop_response_stream() {
  if [[ "$streaming" == "true" ]]; then
    call "$BASE_URL/conversations/messages/$assistant_message_id/stop-streaming/" -o /dev/null -d "{}"
    printf "\n$BG[Interrupted]$CLR"
  else
    exit
  fi
}

dash() {
  printf "$BG%$(tput cols)s$CLR" | tr " " "—"
  echo
}

start_chat_session() {
  conversation_id="$1"

  while true; do
    local queryfile="/tmp/sdai-query-$conversation_id.md"

    printf "$BG==>$CLR "

    message=$(cat)

    if [[ "$message" = "/parker" ]]; then
      parker
      continue
    fi

    if [[ "$message" = "/model" ]]; then
      pick_model
      continue
    fi

    if [[ "$message" = "/view" ]]; then
      nvim -R $CURRENT_RESPONSE_FILE
      continue
    fi


    if [[ "$message" = "/viewdiff" ]]; then
      cat $CURRENT_RESPONSE_FILE | sed -n '/^```diff$/,/^```$/p' | sed '/^```/d' | nvim -R -
      continue
    fi

    if [[ "$message" = "" ]]; then
      editor "$queryfile"
      message=$(cat "$queryfile")
      echo ""
    fi

    message=$(jq -Rs '.' <<< "$message")

    spinner &
    spinner_id=$!

    response=$(post_user_message "$message" "$model_id" "$conversation_id")
    conversation_id=$(jq -r '.data.conversation_id' <<< "$response")
    assistant_message_id=$(jq -r '.data.assistant_message_id' <<< "$response")

    kill $spinner_id
    wait $! 2>/dev/null
    printf '\b\b\b   \b\b\b'

    dash
    trap stop_response_stream SIGINT

    printf "$BG($model_name)$CLR "
    get_response_stream
    echo

    trap - SIGINT
    dash
  done
}

main() {
  [[ "$#" -lt 1 ]] && echo "Usage: sdai [chat|delete|patch|continue]" && exit 0

  case "$1" in
    "d"|"del"|"delete")
      refresh
      delete_conversation
      ;;
    "p"|"patch")
      refresh
      patch_conversation
      ;;
    "c"|"ch"|"chat")
      refresh &
      start_chat_session
      ;;
    "cont"|"continue")
      refresh
      start_chat_session "$(get_conversation_id)"
      ;;
    *)
      echo "Invalid subcommand. Must be one of: chat, delete, patch, continue" && exit 1
      ;;
  esac
}

main "$@"
